// Re-export from new location for backward compatibility
export {
  HeartbeatCheckTypeSchema,
  HeartbeatConfigSchema,
  ProbeConfigSchema,
  CronConfigSchema,
  GoalTriggerConfigSchema,
  EscalationConfigSchema,
  ScheduleLayerSchema,
  ScheduleTriggerSchema,
  ScheduleEntrySchema,
  ScheduleEntryListSchema,
  ScheduleResultSchema,
  type HeartbeatConfig,
  type ProbeConfig,
  type CronConfig,
  type GoalTriggerConfig,
  type EscalationConfig,
  type ScheduleEntry,
  type ScheduleResult,
} from "../../runtime/types/schedule.js";
